import {
  BNB,
  BNB_TESTNET,
  createClient,
  signerFromPrivateKey,
  type Client,
  type GrantSessionResult,
  type Wallet
} from "@altananetwork/sdk";
import {
  computePreparedActionAuthorizationCommitment,
  type PreparedAction
} from "@kumo/financial-agent-kernel";
import { getAddress, type Address, type Hex } from "viem";
import type {
  AltanaGrantSessionPort,
  AltanaSessionBlueprint
} from "./altana-authority.js";

export interface AltanaSdkRuntimeOptions {
  adminPrivateKey: Hex;
  network: "mainnet" | "testnet";
  expectedWalletAddress?: Address;
}

interface LiveSessionRecord {
  client: Client;
  wallet: Wallet;
  session: GrantSessionResult;
  authorizationCommitment: string;
  expiresAt: number;
}

export interface AltanaExecutionResult {
  authorityRef: string;
  walletAddress: string;
  authorizationCommitment: string;
  callsId: string;
  transactionHash?: string;
  status: "PENDING" | "CONFIRMED" | "FAILED";
}

export interface AltanaRevocationResult {
  authorityRef: string;
  callsId: string;
  transactionHash?: string;
  status: "PENDING" | "CONFIRMED" | "FAILED";
}

/**
 * Live Altana 0.8.0 runtime for Kumo.
 *
 * The admin key is supplied by the host and never emitted by this class.
 * Session signers are generated by Altana and retained only in this in-memory
 * runtime. Kumo stores the opaque authorityRef and public provenance instead.
 */
export class AltanaSdkSessionRuntime implements AltanaGrantSessionPort {
  readonly id = "kumo-altana-sdk-session-runtime-v1";
  private readonly client: Client;
  private readonly adminSigner: ReturnType<typeof signerFromPrivateKey>;
  private readonly chainId: number;
  private walletPromise?: Promise<Wallet & { signer: ReturnType<typeof signerFromPrivateKey> }>;
  private readonly sessions = new Map<string, LiveSessionRecord>();

  constructor(private readonly options: AltanaSdkRuntimeOptions) {
    const network = options.network === "mainnet" ? BNB : BNB_TESTNET;
    this.chainId = network.chainId;
    this.client = createClient({ chains: [network], defaultChainId: network.chainId });
    this.adminSigner = signerFromPrivateKey(options.adminPrivateKey);
  }

  private async wallet(): Promise<Wallet & { signer: ReturnType<typeof signerFromPrivateKey> }> {
    if (!this.walletPromise) {
      this.walletPromise = this.client.createWallet({ signer: this.adminSigner }) as Promise<Wallet & { signer: ReturnType<typeof signerFromPrivateKey> }>;
    }
    const wallet = await this.walletPromise;
    if (this.options.expectedWalletAddress
      && getAddress(wallet.address) !== getAddress(this.options.expectedWalletAddress)) {
      throw new Error("ALTANA_RUNTIME_WALLET_ADDRESS_MISMATCH");
    }
    return wallet;
  }

  async grantSession(input: {
    walletAddress: string;
    permissions: AltanaSessionBlueprint["permissions"];
    expiry: number;
    register: true;
    authorizationCommitment: string;
  }): Promise<{
    walletAddress: string;
    publicKey: string;
    expiry: number;
    transactionHash?: string;
    authorityRef: string;
  }> {
    if (this.chainId !== 56 && this.chainId !== 97) throw new Error("ALTANA_RUNTIME_UNEXPECTED_CHAIN");
    const wallet = await this.wallet();
    if (getAddress(wallet.address) !== getAddress(input.walletAddress)) {
      throw new Error("ALTANA_RUNTIME_GRANT_WALLET_MISMATCH");
    }

    const session = await this.client.grantSession({
      wallet,
      signer: wallet.signer,
      chainId: this.chainId,
      permissions: {
        calls: input.permissions.calls.map((permission) => ({ to: getAddress(permission.to) })),
        spend: input.permissions.spend.map((permission) => ({
          token: getAddress(permission.token),
          limit: permission.limit,
          period: permission.period
        }))
      },
      expiry: input.expiry,
      register: true
    });

    if (getAddress(session.walletAddress) !== getAddress(wallet.address)) {
      throw new Error("ALTANA_RUNTIME_SESSION_WALLET_MISMATCH");
    }
    if (session.expiry !== input.expiry) throw new Error("ALTANA_RUNTIME_SESSION_EXPIRY_MISMATCH");

    const authorityRef = [
      "altana",
      "session",
      this.chainId,
      wallet.address.toLowerCase(),
      session.publicKey.toLowerCase(),
      input.authorizationCommitment.toLowerCase()
    ].join(":");
    this.sessions.set(authorityRef, {
      client: this.client,
      wallet,
      session,
      authorizationCommitment: input.authorizationCommitment,
      expiresAt: input.expiry
    });

    return {
      walletAddress: wallet.address,
      publicKey: session.publicKey,
      expiry: session.expiry,
      ...(session.transactionHash ? { transactionHash: session.transactionHash } : {}),
      authorityRef
    };
  }

  async executePreparedAction(input: {
    authorityRef: string;
    action: PreparedAction;
    now?: string;
  }): Promise<AltanaExecutionResult> {
    const record = this.sessions.get(input.authorityRef);
    if (!record) throw new Error("ALTANA_AUTHORITY_REF_UNKNOWN_OR_NOT_IN_PROCESS");
    const nowMs = input.now ? Date.parse(input.now) : Date.now();
    if (!Number.isFinite(nowMs)) throw new Error("ALTANA_EXECUTION_CLOCK_INVALID");
    if (Math.floor(nowMs / 1000) >= record.expiresAt) throw new Error("ALTANA_SESSION_EXPIRED");
    if (getAddress(input.action.signer) !== getAddress(record.wallet.address)) {
      throw new Error("ALTANA_ACTION_SIGNER_WALLET_MISMATCH");
    }
    const recomputed = computePreparedActionAuthorizationCommitment(input.action);
    if (recomputed.toLowerCase() !== input.action.authorizationCommitment.toLowerCase()) {
      throw new Error("ALTANA_ACTION_AUTHORIZATION_COMMITMENT_INVALID");
    }
    if (input.action.authorizationCommitment.toLowerCase() !== record.authorizationCommitment.toLowerCase()) {
      throw new Error("ALTANA_ACTION_NOT_BOUND_TO_SESSION");
    }
    if (input.action.simulationStatus !== "PASSED") throw new Error("ALTANA_EXECUTION_REQUIRES_PASSED_SIMULATION");

    const result = await record.client.execute({
      session: record.session,
      chainId: this.chainId,
      calls: input.action.calls.map((call) => ({
        to: getAddress(call.to),
        data: call.data as Hex,
        value: BigInt(call.value)
      }))
    });

    return {
      authorityRef: input.authorityRef,
      walletAddress: record.wallet.address,
      authorizationCommitment: record.authorizationCommitment,
      callsId: result.callsId,
      ...(result.transactionHash ? { transactionHash: result.transactionHash } : {}),
      status: result.status
    };
  }

  async revokeAuthority(authorityRef: string): Promise<AltanaRevocationResult> {
    const record = this.sessions.get(authorityRef);
    if (!record) throw new Error("ALTANA_AUTHORITY_REF_UNKNOWN_OR_NOT_IN_PROCESS");
    const wallet = await this.wallet();
    const result = await record.client.revokeSession({
      wallet,
      signer: wallet.signer,
      session: record.session,
      chainId: this.chainId
    });
    if (result.status === "CONFIRMED") this.sessions.delete(authorityRef);
    return {
      authorityRef,
      callsId: result.callsId,
      ...(result.transactionHash ? { transactionHash: result.transactionHash } : {}),
      status: result.status
    };
  }
}
